
#ifndef LUCID_FRONTEND_TYPE_INFERENCE_H
#define LUCID_FRONTEND_TYPE_INFERENCE_H

include "mlir/IR/OpBase.td"

def ShapeInferenceOpInterface : OpInterface<"ShapeInference"> {
  let description = [{
    Interface to access a registered method to infer the return types for an
    operation that can be used during type inference.
  }];

  let methods = [
    InterfaceMethod<"Infer and set the output shape for the current operation.",
                    "void", "inferShapes">
  ];
}

#endif // LUCID_FRONTEND_TYPE_INFERENCE_H
